### ISSUE TITLE
E0308 mismatched types: perhaps two different versions of a crate are being used

### ISSUE THREAD

**Issue by jo3bingham** [gklijs/schema_registry_converter#21]
**Describe the bug**
My team ran into an issue with having `schema_registry_converter` and `avro-rs` as dependencies where if the versions don't match our build fails. I opened an issue with `cargo`, so you can find more information here: https://github.com/rust-lang/cargo/issues/8178

**To Reproduce**
1. Add `schema_registry_converter` and `avro-rs` as dependencies, but set the `avro-rs` version to something before the latest: `avro-rs = "0.7.0"`
2. Try to build.

**Notes**
[This comment](https://github.com/rust-lang/cargo/issues/8178#issuecomment-621238239) adds some more details to the situation.

**Comment by gklijs** [comment]
Thanks. Trying to get a new version out in a couple of weeks, with the new avro-rs dependency, support for Protubuf and JSON through schema registry, and Confluent Cloud. Hope I'll have the time.

**Comment by gklijs** [comment]
I might make it so you need a feature flag + avro-rs dependency to use avro, not sure if that works. In the Java world you can make depencies 'provided' not sure a similar approach for rust is possible.

**Comment by jo3bingham** [comment]
Thanks for the quick response!

> In the Java world you can make depencies 'provided' not sure a similar approach for rust is possible.

I’m not sure either, but I can do some research.

**Comment by gklijs** [comment]
It's possible, diesel uses this approach for several features, so I can use that as example to do it similar. The json lib should probably also become optional, since the same problem might occur there. https://github.com/diesel-rs/diesel/blob/0b7bb3c7775b091ce9e48df748b75f2103d36c43/diesel/Cargo.toml#L27

**Comment by gklijs** [comment]
Seems like it's not possible, even with an optional dependency. I'm working on getting the library fully compatible with the latest confluent platform release. Putting different encoders and decoders behind feature flags.

**Comment by gklijs** [comment]
Closing this as it won't be realy fixable. I already updated the dependencies to the ^x.x form like mentiond in one of the things you linked to.
