### ISSUE TITLE
Confluent schema registry sends back a response of "application/vnd.schemaregistry.v1+json"

### ISSUE THREAD

**Issue by kitsuneninetails** [gklijs/schema_registry_converter#3]
The accepted type of just plain "json" actually won't work with schema registry.  Either:

`Accept: application/vnd.schemaregistry.v1+json` 

or 

`Accept: application/json`

is needed in the HTTP request to avoid an error.

Fix proposed in upcoming PR.

**Comment by gklijs** [comment]
Fixed by @kitsuneninetails
