### ISSUE TITLE
QUESTION: How to pas decoder: &'_ mut AvroDecoder <'_> from async move block

### ISSUE THREAD

**Issue by calvinbrown085** [gklijs/schema_registry_converter#37]
Hello! I'm using this example from the `decode` docs in my app, I'm trying to pass `&mut Decoder` 
into a function but getting
```
move occurs because `decoder` has type `schema_registry_converter::async_impl::avro::AvroDecoder<'_>`, which does not implement the `Copy` trait
    | |                                                                               move occurs due to use in generator
```

Has anyone seen this before?
```
/// Decodes bytes into a value.
    /// The choice to use Option<&[u8]> as type us made so it plays nice with the BorrowedMessage
    /// struct from rdkafka, for example if we have m: &'a BorrowedMessage and decoder: &'a mut
    /// Decoder we can use decoder.decode(m.payload()) to decode the payload or
    /// decoder.decode(m.key()) to get the decoded key.
    ///
    /// ```no_run
    /// use rdkafka::message::{Message, BorrowedMessage};
    /// use avro_rs::types::Value;
    /// use schema_registry_converter::async_impl::avro::AvroDecoder;
    /// async fn get_value (
    ///     msg: &'_ BorrowedMessage <'_>,
    ///     decoder: &'_ mut AvroDecoder <'_>,
    /// ) -> Value{
    ///     match decoder.decode(msg.payload()).await{
    ///         Ok(r) => r.value,
    ///         Err(e) => panic!("Error getting value: {}", e),
    ///     }
    /// }
    /// ```
```

**Comment by gklijs** [comment]
It's correct you can't copy it, and you don't want to either, since it's containing the cache. I'm working towards a demo project using async and protobuf, but it could be several weeks or more till it's finished.

I know undeflive had it working, see https://github.com/gklijs/schema_registry_converter/issues/33, but having an async 'real' example would certainly be an improvement. I think using it would require wrapping the decoder in a mutex, but there might be better or other ways. The idea is whenever the decoder is used, the result is cashed, so no matter from which thread, only the first item handeled with the same id, does the http call to get the schema.

**Comment by calvinbrown085** [comment]
Yeah. Okay i'll look into trying a mutex, and yeah I tried the blocking client but ran into the same issue as #33 

I'll let you know what I come up with!

**Comment by gklijs** [comment]
I think ideally you might want a decoder for each 'real' thread. In that case you might fetch the same resource a couple of times, but you never need to wait. But I'm not sure something like that exists. I have little experience with async so far. Looking forward to what you come up with.

**Comment by calvinbrown085** [comment]
```
let sr_settings: SrSettings =
        SrSettings::new("http://avro-schemas.kafka.svc.cluster.local".to_string());
let decoder: Arc<Mutex<AvroDecoder>> = Arc::new(Mutex::new(AvroDecoder::new(sr_settings)));

    let stream_processor = consumer.start().try_for_each(|borrowed_message| {
        let decoder: Arc<Mutex<AvroDecoder>> = Arc::clone(&decoder);

        let owned_message = borrowed_message.detach();

        async move {
            let r: Option<Value> = get_value(owned_message, decoder.lock().unwrap()).await;
            });
            consumer.store_offset(&borrowed_message);
            Ok(())
        }
    });
```
This _compiles_ but i'm not 100% sure that it works.

**Comment by gklijs** [comment]
Since you got an answer and got it to compile again I'm closing this. Would love to know if you got it working.
