### ISSUE TITLE
Implement std::error::Error for SRCError

### ISSUE THREAD

**Issue by MariellHoversholm-Paf** [gklijs/schema_registry_converter#50]
**Is your feature request related to a problem? Please describe.**

The error type does not implement the [standard Error trait](https://doc.rust-lang.org/stable/std/error/trait.Error.html).

**Describe the solution you'd like**

Implement [`std::error::Error`](https://doc.rust-lang.org/stable/std/error/trait.Error.html), optionally behind a feature-gate.

**Describe alternatives you've considered**

None.

**Additional context**

This was discovered while attempting to wrap the error in a [`snafu`](https://docs.rs/snafu/0.6.10/snafu/) enum variant, only to get an error as it does not implement the now fairly old error trait.
To get around this, we opted for a new extension trait to wrap the error with the given type and return `SchemaRegistryErr { source: src_error }.fail()`, where `SchemaRegistryErr` is a variant in the snafu declaration with source tagged `#[snafu(source(false))]`.

**Comment by gklijs** [comment]
Thanks, this would indeed make it easier to use, and should be fully backwards compatible. I'll ad it to the 2.1.0 release. I'll probably can start on that in a week.
