### ISSUE TITLE
Doubt regarding deserialization

### ISSUE THREAD

**Issue by PauloAOliveira** [gklijs/schema_registry_converter#69]
**Is your feature request related to a problem? Please describe.**
In the decode process that exists in async_impl/avro, there is the "decode" function
This function receives the message payload and parses it, spliting the schema id and the message
Where this id is the one which the producer used to generated the message
The decode function uses this id to reach schema registry and load this schema into memory but I may be using a old DTO given that my producer can evolve adding new optional fields, with this I got errors during deserialization.

**Describe the solution you'd like**
Be able to provide the schema version I would like to be used to parse the message, instead of using the one used to produce it

**Describe alternatives you've considered**
Update the DTO before updating the schema, however this would generated a lot of work on events with a lot of consumers

**Additional context**
I did not found a better way to do it, if it exists please forgive my mistake

**Comment by gklijs** [comment]
Sounds a bit similar like how for Java you can use the `specific.avro.reader` option. With which it will use reflection with the full name, to get the schema from the classpath.
But Rust doesn't have reflection. What if there was a `SchemaProvidedDecoder` where you could put in schema's before using it to decode, and it will try to use the schema with the same name each time? In this case giving an error when there is no schema with the correct name, or the schema is incompatible?
