### ISSUE TITLE
Listing subjects and versions

### ISSUE THREAD

**Issue by tzachshabtay** [gklijs/schema_registry_converter#74]
Hi, cool library!

I'm current working on rewriting the backend of a [web ui for kafka and schema registry](https://github.com/tzachshabtay/krowser) (currently written in typescript, rewriting it in rust). It would be cool if we can add (or is it already here and I'm missing it?) the following "admin" functions (basically just nice wrappers around the endpoints):

- [List all subjects](https://docs.confluent.io/platform/current/schema-registry/develop/api.html#get--subjects)
- [List all versions for a subject](https://docs.confluent.io/platform/current/schema-registry/develop/api.html#get--subjects-(string-%20subject)-versions)
- [Get schema for subject+version](https://docs.confluent.io/platform/current/schema-registry/develop/api.html#get--subjects-(string-%20subject)-versions-(versionId-%20version))

Thanks!

**Comment by gklijs** [comment]
Hi, thanks, it's not there yet. But I do plan to expose (make public), and add some things to also make it useful as a schema registry client. So such a list is very helpful.

**Comment by gklijs** [comment]
Hi @tzachshabtay would you still like to have this included, or do you have a workaround by now? I might take a quick look and do it if it's easy anyway. However, I want to have the new release out without pending issues and don't have that much time.

**Comment by tzachshabtay** [comment]
I worked around it, so not needed by anymore, thanks.

**Comment by gklijs** [comment]
Not picking this up for 3.0.0 please let me know by commenting on this issue, if you read this and want it added.
