### ISSUE TITLE
Switch to apache-avro

### ISSUE THREAD

**Issue by tzachshabtay** [gklijs/schema_registry_converter#75]
Hi, so based on this: https://github.com/flavray/avro-rs/pull/99#issuecomment-1017195592, `avro-rs` is not really maintained anymore and the code was contributed to apache-avro, which has added support for named/recursive types (features from the avro spec that current avro-rs does not support).

If this project could switch to the maintained and more fully featured avro library that would be awesome. Thanks.

**Comment by gklijs** [comment]
I fully agree, and want to switch, but they still haven't released. It basically what keeps me from doing a release.

**Comment by martin-g** [comment]
Hi,

Some other Avro users also ask for a new release.
I'll talk to Ryan Skraba (the release manager) to schedule it!

**Comment by gklijs** [comment]
Thanks, last release of avro-rs was already a year ago. I stil have a couple af things I want to include in this libraries 3.0.0 release, but not much. Is there already an issue I can track? Otherwise I just keep checking occasionally.

**Comment by martin-g** [comment]
There are no open issues at ASF JIRA for the Rust module.
I test the open issues from Flavien's repo little by little.

**Comment by ultrabug** [comment]
go @martin-g go ! <3

**Comment by tzachshabtay** [comment]
Hey @martin-g wondering if there were any updates on the release?
Thanks.

**Comment by gklijs** [comment]
I hope so, I have two weeks off from today, so would be nice if I can finish a new release of the converter in that time.

**Comment by martin-g** [comment]
apache-avro 0.14.0 has been released!

**Comment by gklijs** [comment]
@martin-g thanks for notifying. I'll hope to release this or next weekend. Will include the dependency change in that (3.0.0) release.

**Comment by ultrabug** [comment]
Wow I almost can't believe it :+1: congratulations and thanks @martin-g
