### ISSUE TITLE
Provide access to the schema in a DecodeResult ?

### ISSUE THREAD

**Issue by jbruggem** [gklijs/schema_registry_converter#77]
Hello,

Thanks for this amazing project ! 

Is there any way to get the schema of a message when calling `AvroDecoder.decode` ? I have a use case where I need to keep track of the schema.

**Comment by gklijs** [comment]
Not yet, I might add it for the 3.0.0 release. Still kind of waiting for the new Avro release, but also to many other things to do.

**Comment by gklijs** [comment]
I might add this later, feel free to open a PR also.

**Comment by gklijs** [comment]
Fixed and released as 3.1.0

**Comment by jbruggem** [comment]
Amazing ! Thanks :)
