### ISSUE TITLE
Remove or replace failure dependency

### ISSUE THREAD

**Issue by cschaible** [gklijs/schema_registry_converter#78]
**Describe the issue**
The [Cargo.toml](https://github.com/gklijs/schema_registry_converter/blob/v2.1.0/Cargo.toml#L31) file defines a dependency to the `failure` crate. According to this [PR](https://github.com/rust-lang-deprecated/failure/pull/347) here, the library is unmaintained and additionally there is a RUST-SEC [warning](https://rustsec.org/advisories/RUSTSEC-2019-0036) for the library.

**Additional context**
To be honest - I'm not sure if the `schema_registry_converter` is affected at all. Searching for the term `failure` in the github  search returned just the entry in the Cargo.toml (in docker-compose and in a license file). Maybe it was removed / replaced in the past and the entry in the Cargo.toml wasn't removed?

Nevertheless I would appreciate, if the (unused) dependency could be removed or replaced.

**Comment by gklijs** [comment]
I'll look into it. I do vaguely remember there was an pr that did something with the error handling. It might left out removing the dependency.
