### ISSUE TITLE
Working through error with schema_registry_converter

### ISSUE THREAD

**Issue by jaketarnow** [gklijs/schema_registry_converter#9]
Hey @gklijs, moved over to this repo as you mentioned. The code I have been testing is [linked](https://github.com/jaketarnow/rusty-confluent) here. The error that you mentioned is correct: `Could not get avro bytes, was cause by Decoding error: value does not match schema, it's retriable: false, it's cached: false', src/kafka_producer.rs:21:23`. Thanks for all the help!

**Comment by gklijs** [comment]
@jaketarnow got it working, https://github.com/gklijs/rusty-confluent
But with nested structures it's easier to work with a struct. It should be possible to properly support structs with the schema_registry_converter I think. Producer will be relatively simple, by adding some method like 'send_struct' consumer is more difficult. With Java they use the classpath to get the correct object to map to, but I don't know how to do it with rust.
Maybe I could add your example of a nested structure to the docs/test to make the current working more clear?

**Comment by jaketarnow** [comment]
@gklijs Awesome! Yes, something like 'send_struct' should be pretty straightforward. Thanks again for the help. Feel free to add my example to your docs/test.

**Comment by jaketarnow** [comment]
The avro record is able to be written to the topic!, but on the JVM side because Rust ClientConfig doesn't allow to set the key.serializer or value.serializer with `io.confluent.kafka.serializers.KafkaAvroSerializer`. You get this lovely error via JVM: 
```
Caused by: org.apache.kafka.common.errors.SerializationException: Error deserializing Avro message for id -1
Caused by: org.apache.kafka.common.errors.SerializationException: Unknown magic byte!
```
I think one route is by writing the rust code to perform the same type of serialization that is done in the Java based confluent source code. Any thoughts?

**Comment by gklijs** [comment]
Doing the serialization the same way it happens with Java is exactly what the library should do, and it worked like that for me. I could try with Java to get the data out, but I'm surprised you run into this error. Are you sure there is only data from the working example on the topic you try to read from?

**Comment by jaketarnow** [comment]
From my understanding the message should be serialized using the schema registry serializer like you mentioned. Which it technically does via the `encode()`. Yet, if it is not serialized some how, then it won't be able to deserialize it with the schema registry and will produce the `Unknown magic byte!` error which I am getting from the consumer on the JVM side. 

I'm reviewing this to get more clarity https://www.confluent.io/blog/kafka-connect-deep-dive-converters-serialization-explained

**Comment by gklijs** [comment]
It's adding the magic byte, uploading the schema is needed, and also and the schema id to the bytes. It's working in open-bank-mark, https://github.com/openweb-nl/open-bank-mark although in that case the schemas are added in advance, but that should not matter.

**Comment by gklijs** [comment]
@jaketarnow I added a java consumer that is having as output the whole object as json. I really think you still have all records on the topic as I don't know any other explanation.

**Comment by gklijs** [comment]
There is now better schema support, closing this issue.
