### ISSUE TITLE
MessageResolver and IndexResolver Public

### ISSUE THREAD

**Issue by mldmelissa** [gklijs/schema_registry_converter#90]
**Is your feature request related to a problem? Please describe.**
It would be great if the proto_resolver module would be a public module for things such as the MessageResolver and IndexResolver. This is useful when pulling down a schema from a registry and validating producer data with the pulled down schema if the schema has multiple proto messages in it.

**Describe the solution you'd like**
Make the proto_resolver module defined as pub in lib.rs. Or move the IndexResolver and MessageResolver to another public module so that rust apps can access it.

**Additional context**
I am pulling proto schemas from a schema registry by subject, and some of these schemas have multiple message definitions in it. It would be great to use the resolvers to handle this.

**Comment by gklijs** [comment]
Hi,

Somehow missed a notification about this issue. I do understand the value.
Something I was considering, is split the crate up, to have a seperate schema registry cliënt. The additional things needed for Protobuf, mainly the message resolver, might also be a good candidate. I'm not sure when/if I will pick this up. But I would very much appreciate your feedback.

The idea is to keep the main api almost the same.
