### ISSUE TITLE
New Crates.io release?

### ISSUE THREAD

**Issue by simon-an** [gklijs/schema_registry_converter#96]
Hi @gklijs 

really like you create. Would you be so kind and release a new version to crates.io? 

Thx & BR  Simon

**Comment by gklijs** [comment]
@simon-an thanks, Simon. I want to take another go at the two open issues and release 4.0.0 soon.

**Comment by gklijs** [comment]
Just pushed the 4.0.0 release, have fun. I noticed you had a cli tool using this crate.
